### ISSUE TITLE
Prop Types `rotation` and `phase` seem not well defined

### ISSUE THREAD

**Issue by Plopix** [dlbnco/react-moon#3]
Thanks for this lib! It's working like a charm but with 2 warnings

One is about the `rotation` props which can be avoided by setting `rotation="0"` (string is weird but it suppresses the warning)

But I could not get rid of that one.

`Failed prop type: Moon: prop type `phase` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

Thank you!

**Comment by dlbnco** [comment]
Thanks @Plopix!
